"""empty message

Revision ID: d9f79a23f6ca
Revises: 256700e781e3
Create Date: 2022-03-24 15:28:05.763280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f79a23f6ca'
down_revision = '256700e781e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'some_bs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('some_bs', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
